#!/bin/bash
set -e

############################
# 1. VARIABLES
############################
SSH_PORT=2222

declare -A ADMINS

ADMINS["manhhc"]="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv0O0zIYvp8Bx2Ns0ozFeKfDzU/DjkXBydgb68osntDItQndtcHUbdugFo1FSTTAZuvbBd/dYEaTUV1kcJx0tpihZ3SScEXnUFWOxZa1O0bQg+Wr5wUb+e5QuGBmKk/1VzNCEto7Yeba++FdYFb+bQ3uOw3Jpq5bGMOlESvcZe1BY2hO2jUtH2ZwlPLEcLyH00Fuy+PWF rsa-key-manhhc"

############################
# 2. ADMIN USER + SSH KEY
############################
for USER in "${!ADMINS[@]}"; do
    SSH_KEY="${ADMINS[$USER]}"

    if id "$USER" &>/dev/null; then
        echo "User $USER already exists, skip"
        continue
    fi

    useradd -m -s /bin/bash -G sudo "$USER"

    install -d -m 700 /home/$USER/.ssh
    echo "${SSH_KEY}" > /home/$USER/.ssh/authorized_keys
    chmod 600 /home/$USER/.ssh/authorized_keys
    chown -R $USER:$USER /home/$USER/.ssh
done

cat >/etc/sudoers.d/99-admin <<EOF
%sudo ALL=(ALL) NOPASSWD:ALL
EOF
chmod 0440 /etc/sudoers.d/99-admin
